### ISSUE TITLE
MC crashed after rightclick event on entity

### ISSUE THREAD

**Issue by ghost** [RayTrace082/untamedwilds#150] opened 2022-05-10 15:31 UTC
**Describe the bug**
MC crashes on interact with entity holding a block

**Steps To Reproduce**
Rightclick on an "Untamedwilds entity" with a block and the Server will crash

**Crash Log**
https://pastebin.com/dcUc6BRc

**Version:**
 - Minecraft version: [1.18.2]
 - Version of the mod: [untamedwilds-1.18.2-2.1.2]

**Comment by PAIIN2** [comment] 2022-05-13 03:15
Is there a way to solve this issue? Has anyone found a fix?

**Comment by RayTrace082** [comment] 2022-05-16 22:31
Duplicate of #126  (and fixed)

**Closed as completed by RayTrace082** 2022-05-16 22:31 UTC
Labels: bug
