### ISSUE TITLE
game crashes while on loading screen when optifine isnt used and i cant join my aternos server with the same version of the mod when i use optifine for some reason

### ISSUE THREAD

**Issue by Hakkibey1** [RayTrace082/untamedwilds#57] opened 2021-09-12 16:53 UTC
[crash-2021-09-12_19.45.38-fml.txt](https://github.com/RayTrace082/untamedwilds/files/7149957/crash-2021-09-12_19.45.38-fml.txt)
above is the one without optifine

**Comment by RayTrace082** [comment] 2021-09-17 19:55
Duplicate of #24

**Closed as completed by RayTrace082** 2021-09-17 19:55 UTC
