### ISSUE TITLE
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: untamedwilds:egg_tarantula_black_and_whıte

### ISSUE THREAD

**Issue by Onat125** [RayTrace082/untamedwilds#27] opened 2021-07-05 20:39 UTC
[crash-2021-07-05_23.34.47-fml.txt](https://github.com/RayTrace082/untamedwilds/files/6766156/crash-2021-07-05_23.34.47-fml.txt)

**Comment by RayTrace082** [comment] 2021-07-19 14:38
Duplicate of #24

**Closed as completed by RayTrace082** 2021-07-19 14:38 UTC
