### ISSUE TITLE
Cage Trap Shulker Issue

### ISSUE THREAD

**Issue by ehinners** [RayTrace082/untamedwilds#153] opened 2022-05-12 01:14 UTC
**Describe the bug**
Cage Traps will NOT open after being placed back down if the mob inside is a shulker

**Steps To Reproduce**
1. Put a shulker in a "vehicle", such as a boat or minecart
2. Move vehicle over a cage trap
3. Cage trap will take shulker out of vehicle, leaving empty vehicle
4. Break/Pick up trap (opening the trap during this step will have normal/intended behavior)
5. Place trap somewhere else
6. Attempt to open trap
7. Nothing happens

**Version (please complete the following information):**
 - Minecraft version: 1.18.2
 - Version of the mod: Release Date 4/11

**Comment by RayTrace082** [comment] 2022-05-12 10:14
Vanilla strikes again...

Turns out that, if a mob is a "passenger" (in a boat, Horse or whatever) Minecraft discards its NBT data if you try to save it normally, leading to this issue. The issue isn't really due to Shulkers, and any mob will trigger it if you try to catch them from a boat

It's fixed now, and will be released in the next version

Worth noting, Shulkers will instantly teleport when released, due to them spawning on a collision-less block

**Comment by ehinners** [comment] 2022-05-12 13:26
Wow! That was fast. You're awesome, the mod is awesome, and I love the cage traps as an item!

I used to use the enderio soul jars to move mobs around, but the cage traps are such a cool vanilla way to solve the same problem.

Looking forward to the update!

**Closed as completed** 2022-05-16 22:28 UTC
Labels: bug
