### ISSUE TITLE
[1.16.5] [1.5.7] Server datapack appears to not work, but works on client-side

### ISSUE THREAD

**Issue by antibang** [RayTrace082/untamedwilds#158] opened 2022-05-17 07:17 UTC
**Describe the bug**
This might be my own fault and just didn't read something fully, so I apologize in advance if this is the case :)

I made a datapack for Untamed Wilds, and had been testing it singleplayer worlds since I started making it. Everything was working correctly and as intended. Today, I finally had the chance to get on my servers since adding Untamed Wilds and noticed that some entities were spawning in the incorrect biomes, incorrect sizes, etc. Players never said anything because they most likely were never working correctly in the first place. I host 2 servers with my modpack, and this issue happens on both of them as well.

Configs and datapacks are identical on the server and the client. I feel like I just made a mistake, or just missed a disclaimer or something. While looking through closed issues before writing this, I did see where you mentioned you don't suggest disabling mobs through the config file (which I did, but didn't see that until much too late lol), and it should be done through the datapack. Could this possibly be the issue, or something similar?

Also, the datapack still works completely fine in singleplayer. As intended.

Here is a log/debug. Didn't know what would be the most useful:

[latest.log](https://github.com/RayTrace082/untamedwilds/files/8705998/latest.log)

[debug.log](https://github.com/RayTrace082/untamedwilds/files/8706000/debug.log)

I can try to include anything else that you might need as well :)

**Version (please complete the following information):**
 - Minecraft version: 1.16.5
 - Version of the mod: 1.5.7
 - Additional mods: I think this would be in the log/debug, or I'm just being lazy and don't want to list 195 or so mods ;(

**Comment by RayTrace082** [comment] 2022-05-17 08:29
You should be able to check which datapacks are loaded and working in your instance with the `datapack list [available|enabled]` command, could you check if the custom pack appears in either of those lists?

And just to rule out a botched install, do any other datapacks work correctly? The process of installing a datapack is a bit different in a server

Also, a datapack won't retroactively change parts of the world/mobs that have already been generated. While it should be safe (as in, not crash the game), you can expect strange behavior if you remove variants from certain mobs.

**Comment by antibang** [comment] 2022-05-17 08:44
Oh, oops :( I should've mentioned I use a mod called Global Data- & Resourcepacks to load the datapacks on the server (if it means anything to you, I use the 1.7.4 version, and not the newest one because I prefer it), and not through the actual datapack folder inside the world's folder. So, none of the datapacks show up using that command. Should I try adding the datapacks to the world folder that to see if it makes a difference? Tbh, I was going to, but I didn't know exactly how to do it that way, or if it was any different than adding it to the `global_data_packs` folder provided by that mod.

Anyways, yes, all other datapacks are indeed working correctly on the server. I've made sure to generate a couple dozen new mobs in the worlds on both servers, *just* to double-check and still nothin.

**Comment by RayTrace082** [comment] 2022-05-22 21:12
Uh... I myself use OpenLoader to load datapacks, but I just tested loading a datapack on a local server (the vanilla way), and the datapack works as intended in both SP and MP

What does your datapack do? And how did you do it? (since there's multiple ways to disable a mob, but editing 'spawn_types' was only added in 1.18). Can you share your datapack so I can look further into it?

**Comment by antibang** [comment] 2022-05-24 00:58
Well, I only "disabled" a few variants of the tarantula by removing their spawn biomes, and wasn't even sure if it worked, but I haven't seen any around. The only other thing I did was alter the size of some variants of the mobs and changed only a handful of the group sizes. Nothing else was changed.

This is a shortened version of my datapack, only including Untamed Wilds, and not any other mod's datapacks, like it normally has.

I apologize for the cluster of a mess the spawn biomes are for most mobs in advance :)

[baers_additions.zip](https://github.com/RayTrace082/untamedwilds/files/8758770/baers_additions.zip)

**Comment by antibang** [comment] 2022-05-31 11:12
I have an update: so, I was able to get some free time and mess around with my servers and turns out putting the datapack directly into the world's datapacks folder works for some reason.

I haven't been modding myself for that long, and don't know very much about anything, but could it possibly be that Untamed Wilds loads the entity's data _after_ the mod Global Data- & Resourcepacks loads data, thus taking priority over the custom datapack? Or something along those lines. Dunno, just brainstorming :)

**Comment by RayTrace082** [comment] 2022-06-04 22:45
Didn't post anything else, because I couldn't diagnose anything weird, the datapack 100% works in both SP and in a dev server without any issue whatsoever (of course, with the limitation that I can't test it with more than 1 player)

My only conclusion is that Global Data doesn't play well when modders add their own custom loaders into the datapack events (which, is perfectly reasonable, datapacks were never meant to define content)

Will close the issue in a couple days, given that the issue isn't really something I can fix on my end, and can be easily bypassed through a manual install

**Closed as completed** 2022-06-12 13:50 UTC
Labels: bug
