### ISSUE TITLE
critters is not spawning

### ISSUE THREAD

**Issue by turkey32** [RayTrace082/untamedwilds#236] opened 2023-05-25 02:39 UTC
critters, like snakes, tortoises, newts and other animals are not spawning correctly, whenever I find a burrow, a message appears that the 0 creatures stored inside it and 4 spawned.

version : [1.19.2]
mod version : [3.0.1]

**Comment by RayTrace082** [comment] 2023-05-27 12:52
duplicate of #229

**Closed as completed by RayTrace082** 2023-05-27 12:52 UTC
