### ISSUE TITLE
Failure message: Untamed Wilds (untamedwilds) has failed to load correctly

### ISSUE THREAD

**Issue by ElifDidemErguven** [RayTrace082/untamedwilds#40] opened 2021-08-02 02:17 UTC
I created a mod pack with untamed wilds in it i am getting an error message and the server wont launch. Can you tell me how i can fix this?

> -- MOD untamedwilds --
Details:
        Mod File: untamedwilds-1.16.5-1.3.1.jar
        Failure message: Untamed Wilds (untamedwilds) has failed to load correctly
                net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: untamedwilds:egg_tarantula_black_and_wh²te
        Mod Version: 1.1.0
        Mod Issue URL: https://github.com/RayTrace082/untamedwilds/issues
        Exception message: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: untamedwilds:egg_tarantula_black_and_wh²te
Stacktrace:
        at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:classloading,xf:OptiFine:default,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:42) ~[?:?] {re:classloading,xf:OptiFine:default,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraftforge.registries.DeferredRegister.register(DeferredRegister.java:114) ~[forge:?] {re:classloading}
        at untamedwilds.init.ModItems.registerSpawnItems(ModItems.java:100) ~[untamedwilds:1.16.5-1.3.1] {re:classloading}
        at untamedwilds.UntamedWilds.<init>(UntamedWilds.java:54) ~[untamedwilds:1.16.5-1.3.1] {re:classloading}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_291] {}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_291] {}
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_291] {}
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_291] {}
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_291] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_291] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_291] {}

**Comment by RayTrace082** [comment] 2021-08-14 15:07
Duplicate of #24

**Closed as completed by RayTrace082** 2021-08-14 15:07 UTC
