### ISSUE TITLE
Too many snakes! (I can't found any cub either)

### ISSUE THREAD

**Issue by FranPlayer40** [RayTrace082/untamedwilds#42] opened 2021-08-04 15:09 UTC
Hello, I am having problems with the snakes, they are generating too many, this causes that in some areas there is lag and also they are aggressive towards almost any mob, one of these got into my pen and killed most of my cows, it is normal that appear so many or is it a bug? If there is any way to change this in any configuration file I would like you to tell me.

PS: I can't find any babies of any kind, do I have to follow a specific step to make them appear or is it normal that none appear?

(Sorry for my bad English)

**Comment by FranPlayer40** [comment] 2021-08-04 15:10
![1](https://user-images.githubusercontent.com/71850839/128206020-c4a3662d-480d-4903-8a93-dead68629cf4.png)
![2](https://user-images.githubusercontent.com/71850839/128206099-8f6defd8-a3ac-440e-a32b-660e49d4970b.png)

**Comment by RayTrace082** [comment] 2021-08-05 09:04
Babies do not spawn in the wild, you need to breed them yourself by keeping two animals of opposite genders happy (well fed and alone, or whatever you have set in the config)

Chances are that there's a Snake burrow somewhere near spawning all those Adders, killing/removing the snakes and breaking the burrow will solve your problem. Your only other option is disabling Snakes in the config file, but you should never change that in an existing world

On the next version, there will be a cooldown when it comes to hunting, so wild mobs will hunt, at most, twice a day

Closing this issue since everything works as intended

**Closed as completed by RayTrace082** 2021-08-05 09:04 UTC
