### ISSUE TITLE
[1.16.5] [1.5.4] Servers do not work at all.

### ISSUE THREAD

**Issue by Cixon** [RayTrace082/untamedwilds#123] opened 2022-04-09 06:57 UTC
**Describe the bug**
Joining a forge server with Untamed Wilds installed prompts "Failed To Synchronize Registry Data From Server" error to client. Uninstalling mod fixes the issue.

**Steps To Reproduce**
1. Install any 1.16 forge server.
2. Install 1.5.4 Untamed wilds on both client and server.
3. Join the server.
4. See error.

**Crash Log**
N/A

**Screenshots**
N/A

**Version (please complete the following information):**
 - Minecraft version: 1.16
 - Version of the mod: 1.5.4
 - Additional mods: N/A

**Comment by RayTrace082** [comment] 2022-04-10 14:55
>"Failed To Synchronize Registry Data From Server"

These errors can arise from a version mismatch between the server and the client, I can't do anything about it anyways without a log from the server

**Comment by Cixon** [comment] 2022-04-11 19:05
> > "Failed To Synchronize Registry Data From Server"
> 
> These errors can arise from a version mismatch between the server and the client, I can't do anything about it anyways without a log from the server

I’ll get a log later today.

**Comment by Cixon** [comment] 2022-04-16 00:19
**got it here (line 1009):**
[latest.log](https://github.com/RayTrace082/untamedwilds/files/8498973/latest.log)

**additional context:** can confirm i am using the same version for both client and server. this error could arise from a variety of reasons...perhaps it has something to do with a different mod that might be contesting with some of your code? not sure..but i do know that this error does not occur when i uninstall untamedwilds.

**Comment by RayTrace082** [comment] 2022-04-16 13:01
Alright, I think I know the cause

Either the server or the client (if I am reading the log correctly, the client) has disabled Newts in the config, while the other side has not done so, so there is a mismatch where the server expects those items to exist, but the client doesn't have them

Either copy your client's config into the server, or pull the server's config into your client, and the issue should be resolved

Also, consider not touching the config parameters to disable mobs at all, since they no longer work and will be removed soon (datapacks are the intended way to disable mobs, since they don't cause these kinds of issues)

**Comment by Cixon** [comment] 2022-04-19 20:53
> Alright, I think I know the cause
> 
> Either the server or the client (if I am reading the log correctly, the client) has disabled Newts in the config, while the other side has not done so, so there is a mismatch where the server expects those items to exist, but the client doesn't have them
> 
> Either copy your client's config into the server, or pull the server's config into your client, and the issue should be resolved
> 
> Also, consider not touching the config parameters to disable mobs at all, since they no longer work and will be removed soon (datapacks are the intended way to disable mobs, since they don't cause these kinds of issues)

okay, will there be a fix for this soon?

**Comment by RayTrace082** [comment] 2022-04-22 10:13
You could have fixed it yourself the whole time by changing the configs to match the server? 

Don't know how soon it will be fixed, since this "issue" is 100% user-inflicted and there's more important stuff to adress

**Comment by Cixon** [comment] 2022-04-22 17:06
> You could have fixed it yourself the whole time by changing the configs to match the server?
> 
> Don't know how soon it will be fixed, since this "issue" is 100% user-inflicted and there's more important stuff to adress

I understand and you’re correct however nearly every mod in existence doesn’t have this issue when the server config is different than the clients. Usually the server reads the config and allows all connections while utilizing the new configuration.

**Comment by RayTrace082** [comment] 2022-04-24 19:11
Yes, because I am stupid and thought that giving some "power to the users" could be a neat thing to do

Becoming a modder made me realize why every other mod dev eventually ends up abandoning all these ideas

**Closed as completed** 2022-05-16 22:29 UTC
Labels: bug
