### ISSUE TITLE
Animals stuck in dying animation

### ISSUE THREAD

**Issue by TheWookofWallST** [RayTrace082/untamedwilds#182] opened 2022-07-30 01:29 UTC
**Describe the bug**
On my server with your mod on it i keep running into snakes and turtles and other small animals that are stuck getting damage, they are still moving around but they are red and stuck between dying animations 

**Steps To Reproduce**
I've restarted my server seems to be only happening to small UntamedWild animals only started happening when I added Majrusz's Progressive Difficulty and stopped when I removed it.

**Screenshots**
![2022-07-29_20 23 19](https://user-images.githubusercontent.com/68366143/181863072-0cf08ee6-2e86-4b94-b1ac-24e210bbb043.png)

**Version (please complete the following information):**
 - Minecraft version: 1.18.2
 - Version of the mod: 2.1.3
 - Additional mods: 
 - I think it might be an issue with Majrusz's Progressive Difficulty
[modlist.txt](https://github.com/RayTrace082/untamedwilds/files/9224039/modlist.txt)

**Comment by TheWookofWallST** [comment] 2022-07-30 02:02
You could actually probably close this issue I've started noticing it happening with other mod's mobs after exploring a while.

**Comment by RayTrace082** [comment] 2022-07-31 15:36
Okay, gonna close this issue, feel free to reopen/create a new one if you find out it's caused by Untamed Wilds

**Closed as completed by RayTrace082** 2022-07-31 15:36 UTC
Labels: bug
